### ISSUE TITLE
VC 2012 express missing files when trying to compile 

### ISSUE THREAD

**Issue by meiry** [chukong/FantasyWarrior3D#192]
im using VC 2012 express when trying to compile the PrebuiltRuntimeLua.exe
im getting this errors:

..\ui\UIWebViewImpl-win32.cpp(30): fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory
5>game.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.

i guess you are using the Full version of VC ++ not express

**Comment by fusijie** [comment]
It's fixed now.
