### ISSUE TITLE
is there a javascript version?

### ISSUE THREAD

**Issue by Juude** [chukong/FantasyWarrior3D#209]
is there a javascript version? the download speed of github in China is too slow, how about making a copy to gitlab or somewhere else.

**Comment by fusijie** [comment]
yes, I will get it for you tomorrow.

**Comment by fusijie** [comment]
The download link: [http://store.cocos.com/stuff/show/80.html](http://store.cocos.com/stuff/show/80.html)

**Comment by Juude** [comment]
Thanks！
